name = "Indecisive Pack"
author = "ArtificialDan"
version = "0.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec2f52daa2b6f88616df17f0a8b012c257b4b988899bd1e8870aca65566930e0"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
